### ISSUE TITLE
Admin: editing raffle doesnt work :(

### ISSUE THREAD

**Issue by msvrtan** [zgphp/joindin-raffler-backend#164]
To reproduce:

1) Log into admin
2) Click on raffles
3) Click edit on any

**Comment by HcsOmot** [comment]
~~This is also applicable to other entities that are handled by the easy admin backend.~~

~~I have a partly working solution for editing issues, but we need to reconsider which properties (on each entity) should be mutable.~~

~~Also, creating **new** records for entities doesn't work, due to entities having constructor parameters.~~
~~I'm looking into this problem.~~

~~Tagging @msvrtan for request for comments and suggestions.~~
  
**NOTES:**
**SEE ISSUE #175 FOR CLARIFICATION ON JOINDIN * ENTITY EDITING**
**WE STILL NEED TO BE ABLE TO EDIT RAFFLE**
